// <auto-generated />
using System;
using Challenge.CRM.Rommanel.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Challenge.CRM.Rommanel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rommanel")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Challenge.CRM.Rommanel.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("OriginDate")
                        .HasColumnType("date")
                        .HasColumnName("origin_date");

                    b.Property<string>("StateRegistration")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state_registration");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_customers_id");

                    b.ToTable("customers", "rommanel");
                });

            modelBuilder.Entity("Challenge.CRM.Rommanel.Infrastructure.Persistence.EventStore.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_customer_events_id");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_customer_events_aggregate_id");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_events_aggregate_version");

                    b.ToTable("customer_events", "rommanel");
                });

            modelBuilder.Entity("Challenge.CRM.Rommanel.Domain.Entities.Customer", b =>
                {
                    b.OwnsOne("Challenge.CRM.Rommanel.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers", "rommanel");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("Challenge.CRM.Rommanel.Domain.ValueObjects.FederativeUnit", "FederativeUnit", b2 =>
                                {
                                    b2.Property<Guid>("AddressCustomerId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Abbreviation")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("federative_unit");

                                    b2.HasKey("AddressCustomerId");

                                    b2.ToTable("customers", "rommanel");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressCustomerId");
                                });

                            b1.OwnsOne("Challenge.CRM.Rommanel.Domain.ValueObjects.PostalCode", "PostalCode", b2 =>
                                {
                                    b2.Property<Guid>("AddressCustomerId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("postal_code");

                                    b2.HasKey("AddressCustomerId");

                                    b2.ToTable("customers", "rommanel");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressCustomerId");
                                });

                            b1.Navigation("FederativeUnit")
                                .IsRequired();

                            b1.Navigation("PostalCode")
                                .IsRequired();
                        });

                    b.OwnsOne("Challenge.CRM.Rommanel.Domain.ValueObjects.Document", "Document", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("document_type");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("Number")
                                .IsUnique()
                                .HasDatabaseName("uq_customers_document_number");

                            b1.ToTable("customers", "rommanel");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("Challenge.CRM.Rommanel.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("uq_customers_email");

                            b1.ToTable("customers", "rommanel");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("Challenge.CRM.Rommanel.Domain.ValueObjects.Telephone", "Telephone", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("telephone");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers", "rommanel");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Telephone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
