# services:
#   challenge.crm.rommanel.api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=8080
#       - ASPNETCORE_HTTPS_PORTS=8081
#     ports:
#       - "8080"
#       - "8081"
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#       - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#       - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
#       - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
 
# Overrides para desenvolvimento local

name: crm-clientes

services:

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    volumes:
      # Hot reload de appsettings em dev
      - ./src/CRM.Clientes.API/appsettings.Development.json:/app/appsettings.Development.json:ro

  postgres:
    ports:
      - "5432:5432" # expõe para tools locais (DBeaver)

  keycloak:
    ports:
      - "8080:8080" # expõe painel admin local