# Overrides para desenvolvimento local

name: crm-clientes

services:

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    volumes:
      # Hot reload de appsettings em dev
      - ../backend/src/Challenge.CRM.Rommanel.Api/appsettings.Development.json:/app/appsettings.Development.json:ro

  postgres:
    ports:
      - "5432:5432" # expõe para tools locais (DBeaver)

  keycloak:
    ports:
      - "8080:8080" # expõe painel admin local